// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {history} from '../models';
import {runner} from '../models';

export function CancelSpeedTest():Promise<void>;

export function CheckGameServers(arg1:string):Promise<main.GameCheckResult>;

export function GetHistory(arg1:number):Promise<Array<history.Record>>;

export function GetVersion():Promise<string>;

export function LaunchGame(arg1:string):Promise<void>;

export function ListServers():Promise<Array<runner.Server>>;

export function RunSpeedTest(arg1:main.SpeedTestConfig):Promise<void>;
