// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSpeedTest() {
  return window['go']['main']['App']['CancelSpeedTest']();
}

export function CheckGameServers(arg1) {
  return window['go']['main']['App']['CheckGameServers'](arg1);
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LaunchGame(arg1) {
  return window['go']['main']['App']['LaunchGame'](arg1);
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function RunSpeedTest(arg1) {
  return window['go']['main']['App']['RunSpeedTest'](arg1);
}
